plugins {
    id 'java'
    id "com.github.node-gradle.node" version "7.0.2"
    id "io.freefair.lombok" version "8.13"
    id "run.halo.plugin.devtools" version "0.6.1"
}

group 'top.mczhengyi'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('run.halo.tools.platform:plugin:2.22.0')
    compileOnly 'run.halo.app:api'

    testImplementation 'run.halo.app:api'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

node {
    nodeProjectDir = file("${project.projectDir}/console")
}

tasks.register('downloadDependencies') {
    doFirst {
        if (!System.properties['os.name'].toLowerCase().contains('windows')) {
            // 在非 Windows 系统上添加执行权限
            exec {
                commandLine 'chmod', '+x', 'download_dist.sh'
            }
        }
    }
    doLast {
        if (System.properties['os.name'].toLowerCase().contains('windows')) {
            exec {
                commandLine 'cmd', '/c', 'download_dist.bat'
            }
        } else {
            exec {
                commandLine 'bash', '-c', './download_dist.sh'
            }
        }
    }
}

tasks.register('installDepsForUI', PnpmTask) {
    args = ['install']

   dependsOn('downloadDependencies')
}

tasks.register('buildFrontend', PnpmTask) {
    args = ['build']

    dependsOn('installDepsForUI')
}

build {
    // build frontend before build
    tasks.named('compileJava').configure {
        dependsOn('buildFrontend')
    }
}

halo {
    version = '2.21'
    superAdminUsername = 'admin'
    superAdminPassword = 'admin'
    externalUrl = 'http://localhost:8090'
    debug = true
}